server:
  port: 8089
spring:
  application:
    name: service-statistics
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: Sxx15963559164
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.101:8848
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    livereload:
      port: 35739

# 不使用默认的log4j
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/sxx/statisticsservice/mapper/xml/*.xml